image: node:18.20.0

pages:
  stage: build
  cache:
    key:
      files:
        - pnpm-lock.yaml
    paths:
      - .pnpm-store
  variables:
    NITRO_PRESET: gitlab_pages
  before_script:
    - corepack enable
    - corepack prepare pnpm@latest-9 --activate
    - pnpm config set store-dir .pnpm-store
    - pnpm install
  script:
    - pnpm generate
  artifacts:
    paths:
      - .output/public
  publish: .output/public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
