image: node:18.20.0

pages:
  stage: build
  script:
    - echo "Building..."
  artifacts:
    paths:
      - .output/public
  publish: .output/public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
